// flow-typed signature: b7ffeae986a5978b6826caf9cdff226b
// flow-typed version: <<STUB>>/@solana/buffer-layout_v3.0.0/flow_v0.160.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@solana/buffer-layout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@solana/buffer-layout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@solana/buffer-layout/lib/Layout' {
  declare module.exports: any;
}

// Filename aliases
declare module '@solana/buffer-layout/lib/Layout.js' {
  declare module.exports: $Exports<'@solana/buffer-layout/lib/Layout'>;
}
