// flow-typed signature: 65e18196703cbb222ea294226e99826d
// flow-typed version: <<STUB>>/mkdirp-promise_v5.0.1/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mkdirp-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mkdirp-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mkdirp-promise/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mkdirp-promise/lib/index.js' {
  declare module.exports: $Exports<'mkdirp-promise/lib/index'>;
}
