/* Autogenerated SPL Token program C Bindings */

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Specifies the financial specifics of a token.
 */
typedef struct Token_TokenInfo {
    /**
     * Total supply of tokens.
     */
    uint64_t supply;
    /**
     * Number of base 10 digits to the right of the decimal place in the total supply.
     */
    uint64_t decimals;
} Token_TokenInfo;

/**
 * Instructions supported by the token program.
 */
typedef enum Token_TokenInstruction_Tag {
    /**
     * Initializes a new mint and optionally deposits all the newly minted tokens in an account.
     *
     * # Accounts expected by this instruction:
     *
     *   0. `[writable, signer]` New mint to create.
     *   1.
     *      * If supply is non-zero: `[writable]` Account to hold all the newly minted tokens.
     *      * If supply is zero: `[]` Owner of the mint.
     *   2. Optional: `[]` Owner of the mint if supply is non-zero, if present then further
     *      minting is supported.
     */
    InitializeMint,
    /**
     * Initializes a new account.
     *
     * # Accounts expected by this instruction:
     *
     *   0. `[writable, signer]`  New account being initialized.
     *   1. `[]` The mint this account will be associated with.
     *   2. `[]` Owner of the new account.
     */
    InitializeAccount,
    /**
     * Transfers tokens from one account to another either directly or via a delegate.
     *
     * # Accounts expected by this instruction:
     *
     *   0. `[writable]` The source account.
     *   1. `[writable]` The destination account.
     *   2. '[signer]' The source's owner or delegate
     */
    Transfer,
    /**
     * Approves a delegate.  A delegate is given the authority over
     * tokens on behalf of the source account's owner.  If the amount to
     * delegate is zero then delegation is rescinded
     *
     * # Accounts expected by this instruction:
     *
     *   0. `[writable]` The source account.
     *   1. Optional: `[writable]` The delegate if amount is non-zero.
     *   2. `[signer]`The source account owner address
     */
    Approve,
    /**
     * Sets a new owner of a mint or account.
     *
     * # Accounts expected by this instruction:
     *
     *   0. `[writable]` The mint or account to change the owner of.
     *   1. `[]` The new owner
     *   2. `[signer]` The owner of the mint or account.
     */
    SetOwner,
    /**
     * Mints new tokens to an account.
     *
     * # Accounts expected by this instruction:
     *
     *   1. `[writable]` The mint.
     *   2. `[writable]` The account to mint tokens to.
     *   0. `[signer]` The owner of the mint.
     */
    MintTo,
    /**
     * Burns tokens by removing them from an account and the total supply.
     *
     * # Accounts expected by this instruction:
     *
     *   0. `[writable]` The account to burn from.
     *   1. `[writable]` The mint being burned.
     *   2. `[signer]` The owner or delegate address of the account to burn from.
     */
    Burn,
} Token_TokenInstruction_Tag;

typedef struct Token_InitializeMint_Body {
    Token_TokenInfo _0;
} Token_InitializeMint_Body;

typedef struct Token_Transfer_Body {
    uint64_t _0;
} Token_Transfer_Body;

typedef struct Token_Approve_Body {
    uint64_t _0;
} Token_Approve_Body;

typedef struct Token_MintTo_Body {
    uint64_t _0;
} Token_MintTo_Body;

typedef struct Token_Burn_Body {
    uint64_t _0;
} Token_Burn_Body;

typedef struct Token_TokenInstruction {
    Token_TokenInstruction_Tag tag;
    union {
        Token_InitializeMint_Body initialize_mint;
        Token_Transfer_Body transfer;
        Token_Approve_Body approve;
        Token_MintTo_Body mint_to;
        Token_Burn_Body burn;
    };
} Token_TokenInstruction;

typedef uint8_t Token_Pubkey[32];

/**
 * A C representation of Rust's `std::option::Option`
 */
typedef enum Token_COption_Pubkey_Tag {
    /**
     * No value
     */
    None_Pubkey,
    /**
     * Some value `T`
     */
    Some_Pubkey,
} Token_COption_Pubkey_Tag;

typedef struct Token_Some_Body_Pubkey {
    Token_Pubkey _0;
} Token_Some_Body_Pubkey;

typedef struct Token_COption_Pubkey {
    Token_COption_Pubkey_Tag tag;
    union {
        Token_Some_Body_Pubkey some;
    };
} Token_COption_Pubkey;

/**
 * Represents a token type identified by its public key.  Accounts
 * are associated with a specific token type and only accounts with
 * matching types my inter-opt.
 */
typedef struct Token_Token {
    /**
     * Token details.
     */
    Token_TokenInfo info;
    /**
     * Optional owner, used to mint new tokens.  The owner may only
     * be provided during mint creation.  If no owner is present then the mint
     * has a fixed supply and no further tokens may be minted.
     */
    Token_COption_Pubkey owner;
} Token_Token;

/**
 * Account that holds tokens or may delegate tokens.
 */
typedef struct Token_Account {
    /**
     * The mint associated with this account
     */
    Token_Pubkey mint;
    /**
     * The owner of this account.
     */
    Token_Pubkey owner;
    /**
     * The amount of tokens this account holds.
     */
    uint64_t amount;
    /**
     * If `delegate` is `Some` then `delegated_amount` represents
     * the amount authorized by the delegate
     */
    Token_COption_Pubkey delegate;
    /**
     * The amount delegated
     */
    uint64_t delegated_amount;
} Token_Account;

/**
 * Program states.
 */
typedef enum Token_State_Tag {
    /**
     * Unallocated state, may be initialized into another state.
     */
    Unallocated,
    /**
     * A mint.
     */
    Mint,
    /**
     * An account that holds tokens
     */
    Account,
} Token_State_Tag;

typedef struct Token_Mint_Body {
    Token_Token _0;
} Token_Mint_Body;

typedef struct Token_Account_Body {
    Token_Account _0;
} Token_Account_Body;

typedef struct Token_State {
    Token_State_Tag tag;
    union {
        Token_Mint_Body mint;
        Token_Account_Body account;
    };
} Token_State;
