// flow-typed signature: 4f92d81ee3831cb415b4b216cc0679d9
// flow-typed version: <<STUB>>/event-emitter_v0.3.5/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'event-emitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'event-emitter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'event-emitter/all-off' {
  declare module.exports: any;
}

declare module 'event-emitter/benchmark/many-on' {
  declare module.exports: any;
}

declare module 'event-emitter/benchmark/single-on' {
  declare module.exports: any;
}

declare module 'event-emitter/emit-error' {
  declare module.exports: any;
}

declare module 'event-emitter/has-listeners' {
  declare module.exports: any;
}

declare module 'event-emitter/pipe' {
  declare module.exports: any;
}

declare module 'event-emitter/test/all-off' {
  declare module.exports: any;
}

declare module 'event-emitter/test/emit-error' {
  declare module.exports: any;
}

declare module 'event-emitter/test/has-listeners' {
  declare module.exports: any;
}

declare module 'event-emitter/test/index' {
  declare module.exports: any;
}

declare module 'event-emitter/test/pipe' {
  declare module.exports: any;
}

declare module 'event-emitter/test/unify' {
  declare module.exports: any;
}

declare module 'event-emitter/unify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'event-emitter/all-off.js' {
  declare module.exports: $Exports<'event-emitter/all-off'>;
}
declare module 'event-emitter/benchmark/many-on.js' {
  declare module.exports: $Exports<'event-emitter/benchmark/many-on'>;
}
declare module 'event-emitter/benchmark/single-on.js' {
  declare module.exports: $Exports<'event-emitter/benchmark/single-on'>;
}
declare module 'event-emitter/emit-error.js' {
  declare module.exports: $Exports<'event-emitter/emit-error'>;
}
declare module 'event-emitter/has-listeners.js' {
  declare module.exports: $Exports<'event-emitter/has-listeners'>;
}
declare module 'event-emitter/index' {
  declare module.exports: $Exports<'event-emitter'>;
}
declare module 'event-emitter/index.js' {
  declare module.exports: $Exports<'event-emitter'>;
}
declare module 'event-emitter/pipe.js' {
  declare module.exports: $Exports<'event-emitter/pipe'>;
}
declare module 'event-emitter/test/all-off.js' {
  declare module.exports: $Exports<'event-emitter/test/all-off'>;
}
declare module 'event-emitter/test/emit-error.js' {
  declare module.exports: $Exports<'event-emitter/test/emit-error'>;
}
declare module 'event-emitter/test/has-listeners.js' {
  declare module.exports: $Exports<'event-emitter/test/has-listeners'>;
}
declare module 'event-emitter/test/index.js' {
  declare module.exports: $Exports<'event-emitter/test/index'>;
}
declare module 'event-emitter/test/pipe.js' {
  declare module.exports: $Exports<'event-emitter/test/pipe'>;
}
declare module 'event-emitter/test/unify.js' {
  declare module.exports: $Exports<'event-emitter/test/unify'>;
}
declare module 'event-emitter/unify.js' {
  declare module.exports: $Exports<'event-emitter/unify'>;
}
